### ISSUE TITLE
Please give the release tarballs a more descriptive name

### ISSUE THREAD

**Issue by jsquyres** [intel/mpi-benchmarks#15]
On https://github.com/intel/mpi-benchmarks/releases, the download tarballs are named the release number -- e.g., "v2019.1.tar.gz".  This is very confusing when downloading these tarballs into a general "downloads" directory -- there's no indication in the filename what the file is.

Could you please name future release tarballs with a filename that matches the directory name to which the contents expand?  This is a quite common convention.

E.g., if your next release tarball follows the same convention as previous releases, it will be named `v2019.2.tar.gz`, and will expand into a directory named `mpi-benchmarks-2019.2` (note the lack of `v`).  It would be great if the tarball was therefore named `mpi-benchmarks-2019.2.tar.gz`.

I don't have a strong preference as to whether the `v` precedes the `2019` or not -- just as long as the tarball filename matches the directory name to which it expands.

Please consider this for future releases.  Thanks.

**Comment by VinnitskiV** [comment]
@jsquyres 
Fair point, we will fix it in next version.
Thanks!

**Comment by VinnitskiV** [comment]
Fixed.
