### ISSUE TITLE
gcc version dependency

### ISSUE THREAD

**Issue by a-ilango** [intel/mpi-benchmarks#23]
Is there a requirement on the gcc version? I don't see any info regarding this in the README.

I built mpi-benchmarks on a system with older version of gcc (v4.8.5) and it compiled fine but when running benchmarks I got the following error:

```
[0] IMB-MPI1: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by IMB-MPI1)
[0] IMB-MPI1: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by IMB-MPI1)
```

Build info:

```
export CC=/opt/intel/impi/2019.4.243/intel64/bin/mpicc
export CXX=/opt/intel/impi/2019.4.243/intel64/bin/mpicxx
make all
```

If I point LD_LIBRARY_PATH to libraries of latest gcc (v8.2.0) while running the benchmark, it works fine.

**Comment by dong0321** [comment]
I have the same problem as
 ./IMB-MPI1: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./IMB-MPI1)

**Comment by VinnitskiV** [comment]
@a-ilango @dong0321 
Did you run IMB on same machine where you build?
