### ISSUE TITLE
Options for specifying message length while running IMB-MPI1

### ISSUE THREAD

**Issue by aolia-0303** [intel/mpi-benchmarks#31]
Hello,

I would like to know if there are options for specifying message length.

Currently the default message length configuration is:
```
# Minimum message length in bytes:   0
# Maximum message length in bytes:   4194304
```

It seems that  the `-msglen` option is not used to achieve this.

**Comment by VinnitskiV** [comment]
Hi @aolia-0303, thank you for your interest.
For changing message length(like min\max) you need to use -msglog option:
- `mpirun -n 2 IMB-MPI1 -msglog  min_msglog:max_msglog`
For using special sizes(which are not powers of 2) you must to create file(for example lengths.txt) with this  sizes and pass this file like this:
- `mpirun -n 2 IMB-MPI1 -msglen lengths.txt`
You can find more information:
- `IMB-MPI1 -help`
- `IMB-MPI1 -help msglen` 
- `IMB-MPI1 -help msglog`
