### ISSUE TITLE
Livelock in case of memory allocation failure

### ISSUE THREAD

**Issue by EmmanuelBRELLE** [intel/mpi-benchmarks#47]
In some cases  (for example "IMB-MPI1 Pingpong" running with 3 or more processes) some processes are put aside, waiting for others in an MPI_Barrier. If meanwhile other processes fail to allocate memory (message lengths that are too large in comparison to "-mem" arguement), those processes won't reach the MPI_Barrier call. 
"Inactive" processes will then hang forever in MPI_Barrier on MPI_COM_WORLD.

**Comment by JuliaRS** [comment]
@EmmanuelBRELLE,
please run with -mem 999 argument of IMB.

**Comment by JuliaRS** [comment]
@EmmanuelBRELLE  is it still actual for you?

**Comment by EmmanuelBRELLE** [comment]
No that's fine for me. Sorry for late feedback.
