### ISSUE TITLE
IMB is not compiled with OpenMPI 4.0

### ISSUE THREAD

**Issue by dkuzmin72** [intel/mpi-benchmarks#7]
OpenMPI 4.0 removed support of depricated MPI_UB and MPI_LB types.
That's why IMB cannot be compiled with OpenMPI:
IMB_init_transfer.c: In function ‘IMB_init_transfer’:
/ompi4.0/include/mpi.h:1102:53: error: ‘ompi_mpi_lb’ undeclared (first use in this function)
 #define MPI_LB OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_lb)
IMB_init_transfer.c:177:39: note: in expansion of macro ‘MPI_LB’
  bllen[0]=1; displ[0] = 0; types[0] = MPI_LB;

The same error is for MPI_UB.

Command line:
make -f make_mpich MPI_HOME=/ompi4.0

BTW: Why do you reset MPI_HOME? OpenMPI usually sets this environment variable and it should work as simple as:
make -f make_mpich

It's here:
$head -3 make_mpich
(comment) Enter root directory of mpich install
MPI_HOME=

Regards!
---Dmitry

**Comment by dkuzmin72** [comment]
Please commit changes from https://github.com/intel/mpi-benchmarks/pull/6. It should resolve the issue.

**Comment by gpaulsen** [comment]
@ykiryano Would it be possible to commit this soon to allow IMB to be MPI 3.0 standards conforming?  (i.e. not use removed MPI1 datatypes)
